import cvxpy as cp
from ceml.sklearn import generate_counterfactual
#.......

#model = ......
#x_orig = .....
#y_target = .....

# Change optimization parameters
#opt = ....
opt_args = {"epsilon": 10.e-4, "solver": cp.SCS, "solver_verbosity": False, "max_iter": 200}

# Compute counterfactual explanations
x_cf, y_cf, delta = generate_counterfactual(model, x_orig, y_target, features_whitelist=None, C=0.1, regularization="l1", optimizer=opt, optimizer_args=opt_args, return_as_dict=False)
               